Update README.md and test.yaml (#1)

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -21,6 +21,9 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
+env:
+  file: .github/test/test.toml
+
 jobs:
   test:
     name: "Test"
@@ -52,16 +55,9 @@ jobs:
         id: test
         uses: ./
         with:
-          file: ".github/test/test.toml"
-          path: "$.project.authors[0].name"
-          value: "I Made This"
-          write: false
-
-      #- name: "Debug"
-      #  if: ${{ !github.event.act }}
-      #  continue-on-error: true
-      #  run: |
-      #    cat ".github/test/pyproject.toml"
+          file: ${{ env.file }}
+          path: $.project.authors[0].name
+          value: I Made This
 
       - name: "Validate Outputs"
         #if: ${{ !github.event.act }}
@@ -73,14 +69,28 @@ jobs:
             data: '{"title":"TOML Example","project":{"name":"toml-action","dynamic":["version"],"authors":[{"name":"I Made This"}]}}'
             toml:
 
-      - name: "Verify JSON"
-        #if: ${{ !github.event.act }}
+      - name: "Validate JSON"
+        if: ${{ fromJSON(steps.test.outputs.data).project.name != 'toml-action' }}
         run: |
-          echo "name: ${{ fromJSON(steps.test.outputs.data).project.name }}"
-          if [ "${{ fromJSON(steps.test.outputs.data).project.name }}" != "toml-action" ];then
-            echo "Output Invalid: data.project.name"
-            exit 1
-          fi
+          echo "Output Invalid: data.project.name" && exit 1
+
+      - name: "Read Updated TOML File"
+        #if: ${{ !github.event.act }}
+        id: toml
+        uses: ./
+        with:
+          file: ${{ env.file }}
+          path: $.project.authors[0].name
+
+      - name: "Validate Updated Outputs"
+        #if: ${{ !github.event.act }}
+        uses: cssnr/validate-outputs-action@master
+        with:
+          outputs: ${{ toJSON(steps.toml.outputs) }}
+          data: |
+            value: I Made This
+            data: '{"title":"TOML Example","project":{"name":"toml-action","dynamic":["version"],"authors":[{"name":"I Made This"}]}}'
+            toml:
 
       - name: "Schedule Failure Notification"
         if: ${{ failure() && github.event_name == 'schedule' }}
